#!/usr/bin/env bash
#
# Fix HTTP 400 on https://pdfforge.store/ when the IP is shared with another site (e.g. pimux/Django).
# Run ON THE VPS as root:
#   sudo bash setup-pdfforge-on-vps.sh you@yourmail.com
# Optional:
#   SITE_ROOT=/var/www/pdfforge.store sudo -E bash setup-pdfforge-on-vps.sh you@mail.com
#
# Steps: (1) HTTP-only nginx for pdfforge + static root  (2) certbot webroot  (3) HTTPS + reload

set -euo pipefail

EMAIL="${1:-${LETSENCRYPT_EMAIL:-}}"
if [[ -z "${EMAIL}" ]]; then
  echo "Usage: sudo $0 your-email@example.com"
  echo "  (email is for Let's Encrypt registration / expiry notices)"
  exit 1
fi

if [[ "${EUID:-0}" -ne 0 ]]; then
  echo "Run as root: sudo $0 ${EMAIL}"
  exit 1
fi

ROOT="${SITE_ROOT:-/var/www/pdfforge.store}"
CONF="${NGINX_SITE_PATH:-/etc/nginx/sites-available/pdfforge.store}"
ENABLED="/etc/nginx/sites-enabled/pdfforge.store"
DOMAIN_PRIMARY="pdfforge.store"
DOMAINS=(pdfforge.store www.pdfforge.store)

command -v nginx >/dev/null || { echo "nginx not installed"; exit 1; }
mkdir -p "${ROOT}/.well-known/acme-challenge"
chmod -R a+rX "${ROOT}" 2>/dev/null || true

echo "==> (1/3) Install HTTP-only vhost (ACME + static; no TLS yet)"
cat >"${CONF}" <<HTTPONLY
# Auto-generated by setup-pdfforge-on-vps.sh — pdfforge.store HTTP (ACME + static)
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAINS[0]} ${DOMAINS[1]};

    root ${ROOT};
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files \$uri =404;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
HTTPONLY

ln -sf "${CONF}" "${ENABLED}"
nginx -t
systemctl reload nginx

echo "==> (2/3) Obtain TLS certificate (Let's Encrypt, webroot)"
if ! command -v certbot >/dev/null; then
  echo "Installing certbot..."
  apt-get update -qq && apt-get install -y -qq certbot
fi

certbot certonly \
  --webroot -w "${ROOT}" \
  -d "${DOMAINS[0]}" -d "${DOMAINS[1]}" \
  --non-interactive --agree-tos -m "${EMAIL}" \
  --keep-until-expiring

CERT="/etc/letsencrypt/live/${DOMAIN_PRIMARY}/fullchain.pem"
KEY="/etc/letsencrypt/live/${DOMAIN_PRIMARY}/privkey.pem"
if [[ ! -f "${CERT}" || ! -f "${KEY}" ]]; then
  echo "Cert files missing after certbot. Expected:"
  echo "  ${CERT}"
  echo "  ${KEY}"
  exit 1
fi

echo "==> (3/3) Install HTTPS vhost + API proxy (optional)"
cat >"${CONF}" <<FULLCONF
# Auto-generated by setup-pdfforge-on-vps.sh — ${DOMAIN_PRIMARY}
upstream pdfforge_pdf_api {
    server 127.0.0.1:3847;
    keepalive 8;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAINS[0]} ${DOMAINS[1]};

    root ${ROOT};
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files \$uri =404;
    }

    location / {
        return 301 https://${DOMAIN_PRIMARY}\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAINS[0]} ${DOMAINS[1]};

    ssl_certificate     ${CERT};
    ssl_certificate_key ${KEY};
    ssl_early_data off;

    root ${ROOT};
    index index.html;

    large_client_header_buffers 4 32k;

    if (\$host = www.${DOMAIN_PRIMARY}) {
        return 301 https://${DOMAIN_PRIMARY}\$request_uri;
    }

    location /api/ {
        proxy_pass http://pdfforge_pdf_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        client_max_body_size 80m;
        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
FULLCONF

nginx -t
systemctl reload nginx

echo ""
echo "Done. Quick checks:"
echo "  curl -sSI https://${DOMAIN_PRIMARY}/ | head -3"
echo "  curl -sSI https://${DOMAIN_PRIMARY}/bank-transactions.html | head -3"
echo ""
echo "Upload static files from your laptop:  ./deploy.sh"
